CoffeeClubFranchise/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CoffeeClubFranchisee.Models
{
    public class ContactModel
    {
        [Required]
        public string Subject { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public string Phone { get; set; }
        [Required]
        public string Message { get; set; }
        public int RedirectPage { get; set; }
    }
}

CoffeeClubFranchise/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using CoffeeClubFranchisee.Models;
using System.Text;
using System.Net.Mail;
using System.Configuration;

namespace CoffeeClubFranchisee.Controllers
{
    public class ApplicationController : SurfaceController
    {
        [ChildActionOnly]
        public ActionResult FranchiseForm()
        {
            // In case you need it...
            //var currentNode = Umbraco.TypedContent(UmbracoContext.PageId.GetValueOrDefault());

            var model = new ApplicationForm();
            return PartialView("_ApplicationForm", model);
        }


        [HttpPost]
        public ActionResult FranchiseForm(ApplicationForm model)
        {
           // var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new { x.Key, x.Value.Errors }).ToArray();

            if (ModelState.IsValid)
            {
                var sb = new StringBuilder();
                sb.AppendFormat("<p><b>New Franchise Application:</b></p>");

                if (!string.IsNullOrEmpty(model.Name))
                {
                    sb.AppendFormat("<h2>Partner One</h2>");
                    sb.AppendFormat("<p><b>Name:</b> {0}</p>", model.Name);
                    sb.AppendFormat("<p><b>Email:</b> {0}</p>", model.Email);
                    sb.AppendFormat("<p><b>Phone:</b> {0}</p>", model.Phone);
                    sb.AppendFormat("<p><b>Mobile:</b> {0}</p>", model.Mobile);
                    sb.AppendFormat("<p><b>Fax:</b> {0}</p>", model.Fax);
                    sb.AppendFormat("<p><b>DOB:</b> {0}</p>", model.DOB);

                    //Address 
                    sb.AppendFormat("<h3>Address</h3>");
                    sb.AppendFormat("<p><b>Street Address:</b> {0}</p>", model.StreetNumber + " " + model.Address);
                    sb.AppendFormat("<p><b>Town/Suburb:</b> {0}</p>", model.Suburb);
                    sb.AppendFormat("<p><b>City/Region:</b> {0}</p>", model.City);
                    sb.AppendFormat("<p><b>Post Code:</b> {0}</p>", model.Postcode);
                    sb.AppendFormat("<p><b>Country:</b> {0}</p>", model.Country);
                    

                    
                    //Experiences
                    sb.AppendFormat("<h3>Previous Business /Employment Experience</h3>");
                    sb.Append("<table style='border:1px solid black'>");
                    sb.AppendFormat("<tr><td>Years</td><td>Position</td></tr>");
                    if(!string.IsNullOrEmpty(model.Years1)){
                         sb.AppendFormat("<tr><td>{0}</td><td>{1}</td></tr>",model.Years1,model.Position1 );
                    }
                    if(!string.IsNullOrEmpty(model.Years2))
                    {
                         sb.AppendFormat("<tr><td>{0}</td><td>{1}</td></tr>",model.Years2,model.Position2 );
                    }
                    if (!string.IsNullOrEmpty(model.Years3))
                    {
                        sb.AppendFormat("<tr><td>{0}</td><td>{1}</td></tr>", model.Years3, model.Position3);
                    }
                    if (!string.IsNullOrEmpty(model.Years4))
                    {
                        sb.AppendFormat("<tr><td>{0}</td><td>{1}</td></tr>", model.Years3, model.Position4);
                    }
                    if (!string.IsNullOrEmpty(model.Years5))
                    {
                        sb.AppendFormat("<tr><td>{0}</td><td>{1}</td></tr>", model.Years3, model.Position5);
                    }
                    sb.Append("</table>");

                    ///////////////////////////////////////////////////////////////////////////////////////////
                    sb.AppendFormat("<h3>Statement Of Assets and Liabilities</h3>");
                    sb.AppendFormat("<h4>Assets:</h4>");
                    sb.AppendFormat("<p><b>Bank:</b> {0}</p>", model.Bank);
                    sb.AppendFormat("<p><b>Business Investments:</b> {0}</p>",model.BusinessStatement);
                    sb.AppendFormat("<p><b>Real Estate:</b> {0}</p>", model.RealState);
                    sb.AppendFormat("<p><b>Share and Investments:</b> {0}</p>", model.ShareAndInvestment);
                    sb.AppendFormat("<p><b>Other:</b> {0}</p>", model.Other);

                    sb.AppendFormat("<h4>Liabilities:</h4>");
                    sb.AppendFormat("<p><b>Overdrafts:</b> {0}</p>", model.Overdrafts);
                    sb.AppendFormat("<p><b>Mortgages:</b> {0}</p>", model.Mortages);
                    sb.AppendFormat("<p><b>Credit Cards:</b> {0}</p>", model.CreditCards);
                    sb.AppendFormat("<p><b>Other:</b> {0}</p>", model.LiabilitiesOther);
                    sb.AppendFormat("<p><b>Total Liabilities:</b> {0}</p>", model.TotalLiabilities);
                    sb.AppendFormat("<p><b>Total Net Worth:</b> {0}</p>", model.TotalNetWorth);

                    sb.AppendFormat("<h3>Proposed Investment</h3>");
                    sb.AppendFormat("<p><b>Cash:</b> {0}</p>", model.Cash);
                    sb.AppendFormat("<p><b>Loan Type:</b> {0}</p>", model.LoanType);
                    sb.AppendFormat("<p><b>Total:</b> {0}</p>", model.Total);
                    sb.AppendFormat("<p><b>Preferred Location:</b> {0}</p>", model.PreferredLocation);
                    sb.AppendFormat("<p><b>Time Frame:</b> {0}</p>", model.Timeframe);
                    sb.AppendFormat("<br/>");

                    sb.AppendFormat("<p><b>Why have you chosen franchising?</b></p> <p> {0} </p>", model.WhyChosenFranchising);
                    sb.AppendFormat("<p><b>What is it about The Coffee Club that interests you over others in the industry?</b></p> <p> {0} </p>", model.WhatInterestsYouOverOthers);
                    sb.AppendFormat("<p><b>Tell us the motivating factors behind you wanting to own your own business?</b></p> <p> {0} </p>", model.MotivatingFactorsBehindOwn);
                    sb.AppendFormat("<p><b>What do you think will assist in making you a successful franchisee with The Coffee Club?</b></p> <p> {0} </p>", model.AssistMakingSuccessfulFranchisee);
                    sb.AppendFormat("<p><b>Where did you first find out about afranchising opportunity with The Coffee Club?</b></p> <p> {0} </p>", model.FindAboutFranchisingOpportunity);

                }

                if (!string.IsNullOrEmpty(model.Name2))
                {
                    sb.AppendFormat("<h2>Partner Two</h2>");
                    sb.AppendFormat("<p><b>Name:</b> {0}</p>", model.Name2);
                    sb.AppendFormat("<p><b>Fax:</b> {0}</p>", model.Email2);
                    sb.AppendFormat("<p><b>Phone:</b> {0}</p>", model.Phone2);
                    sb.AppendFormat("<p><b>Mobile:</b> {0}</p>", model.Mobile2);
                    sb.AppendFormat("<p><b>Fax:</b> {0}</p>", model.Fax2);
                    sb.AppendFormat("<p><b>DOB:</b> {0}</p>", model.DOB2);

                    //Address 
                    sb.AppendFormat("<h3>Address</h3>");
                    sb.AppendFormat("<p><b>Street Address:</b> {0}</p>", model.StreetNumber2 + " " + model.Address2);
                    sb.AppendFormat("<p><b>Town/Suburb:</b> {0}</p>", model.Suburb2);
                    sb.AppendFormat("<p><b>City/Region:</b> {0}</p>", model.City2);
                    sb.AppendFormat("<p><b>Post Code:</b> {0}</p>", model.Postcode2);
                    sb.AppendFormat("<p><b>Country:</b> {0}</p>", model.Country2);



                    //Experiences
                    sb.AppendFormat("<h3>Previous Business /Employment Experience</h3>");
                    sb.Append("<table style='border:1px solid black'>");
                    sb.AppendFormat("<tr><td>Years</td><td>Position</td></tr>");
                    if (!string.IsNullOrEmpty(model.Years12))
                    {
                        sb.AppendFormat("<tr><td>{0}</td><td>{1}</td></tr>", model.Years12, model.Position12);
                    }
                    if (!string.IsNullOrEmpty(model.Years22))
                    {
                        sb.AppendFormat("<tr><td>{0}</td><td>{1}</td></tr>", model.Years22, model.Position22);
                    }
                    if (!string.IsNullOrEmpty(model.Years32))
                    {
                        sb.AppendFormat("<tr><td>{0}</td><td>{1}</td></tr>", model.Years32, model.Position32);
                    }
                    if (!string.IsNullOrEmpty(model.Years42))
                    {
                        sb.AppendFormat("<tr><td>{0}</td><td>{1}</td></tr>", model.Years32, model.Position42);
                    }
                    if (!string.IsNullOrEmpty(model.Years52))
                    {
                        sb.AppendFormat("<tr><td>{0}</td><td>{1}</td></tr>", model.Years32, model.Position52);
                    }
                    sb.Append("</table>");

                    ///////////////////////////////////////////////////////////////////////////////////////////
                    sb.AppendFormat("<h3>Statement Of Assets and Liabilities</h3>");
                    sb.AppendFormat("<h4>Assets:</h4>");
                    sb.AppendFormat("<p><b>Bank:</b> {0}</p>", model.Bank2);
                    sb.AppendFormat("<p><b>Business Investments:</b> {0}</p>", model.BusinessStatement2);
                    sb.AppendFormat("<p><b>Real Estate:</b> {0}</p>", model.RealState2);
                    sb.AppendFormat("<p><b>Share and Investments:</b> {0}</p>", model.ShareAndInvestment2);
                    sb.AppendFormat("<p><b>Other:</b> {0}</p>", model.Other2);

                    sb.AppendFormat("<h4>Liabilities:</h4>");
                    sb.AppendFormat("<p><b>Overdrafts:</b> {0}</p>", model.Overdrafts2);
                    sb.AppendFormat("<p><b>Mortgages:</b> {0}</p>", model.Mortages2);
                    sb.AppendFormat("<p><b>Credit Cards:</b> {0}</p>", model.CreditCards2);

CoffeeClubFranchise/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using CoffeeClubFranchisee.Models; 
using System.Text;
using System.Net.Mail;
using System.Configuration;

namespace CoffeeClubFranchisee.Controllers
{
    public class ContactController : SurfaceController
    {
        [ChildActionOnly]
        public ActionResult ContactForm()
        {
            // In case you need it...
            //var currentNode = Umbraco.TypedContent(UmbracoContext.PageId.GetValueOrDefault());

            var model = new ContactModel();
            return PartialView("ContactForm", model);
        }


        [HttpPost]
        public ActionResult ContactForm(ContactModel model)
        {
            if (ModelState.IsValid)
            {
                var sb = new StringBuilder();
                sb.AppendFormat("<p><b>Name:</b> {0}</p>", model.Name);
                sb.AppendFormat("<p><b>Email:</b> {0}</p>", model.Email);
                sb.AppendFormat("<p><b>Phone:</b> {0}</p>", model.Phone);
                sb.AppendFormat("<p><b>Subject:</b> {0}</p>", model.Subject);
                sb.AppendFormat("<p><b>Message:</b> {0}</p>", model.Message);

                var Sender = model.Email;
                MailMessage mailMessage = new MailMessage(Sender, "aashish.bhurtel@yahoo.com");
                mailMessage.IsBodyHtml = true;
                mailMessage.Body = sb.ToString();
                mailMessage.Subject = model.Subject;
                SmtpClient smtpClient = new SmtpClient();
                smtpClient.Send(mailMessage);




                TempData["Success"] = "Thanks for your message.";
                return RedirectToUmbracoPage(model.RedirectPage);
            }
            return this.RedirectToCurrentUmbracoPage();
        }

    }
}

CoffeeClubFranchise/Views/Application.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}


<div class="container" style="margin-top:100px;">
    @if (TempData["Captcha2"] != null)
    {
        <script>
            alert("@TempData["Captcha2"]");
        </script>
    }

    @{
        if (TempData["Success"] != null)
        {
            <div class="alert alert-success alert-block fade in" id="successAlert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <p>@TempData["Success"]</p>
            </div><!-- end alert -->
        }
    }

    @{Html.RenderAction("FranchiseForm", "Application");  }
</div>

@{Html.RenderPartial("_FooterBlock");}


@section Javascript
{
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
}

CoffeeClubFranchise/Views/BlogOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var src = Umbraco.Media(CurrentPage.topLevelImage);
}

<div style="text-align:center; width:100%; height:325px; background-size:cover; background-image: url(@src.Url);">
    <div class="container">
        <div id="menuLogoTop">
            <h2>@CurrentPage.name.ToUpper()</h2>
        </div>
    </div>
</div>

<div id="orangeTab" style="height:50px; padding-top:14px;">
    <div class="container">
        <h3>@CurrentPage.name.ToUpper()</h3>
    </div>
</div>





<div role="content">

	<section class="light blogarchive equalizer">
		<div class="container">

			<div class="row">
				@foreach(var post in CurrentPage.Children) 
				{
					<div class="col-sm-6">
						<div class="content equal">
							<a href="@post.Url">
								<div class="date">@post.CreateDate.ToLongDateString()</div>
								<h2>@post.Name</h2>		
								<p>@Umbraco.Truncate(post.Introduction, 240, true)</p>
							</a>
						</div>
					</div>
				}
			</div>
		</div>
	</section>

</div>

CoffeeClubFranchise/Views/BlogPost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@CurrentPage.GetGridHtml("content", "fanoe")

CoffeeClubFranchise/Views/Brand.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var src = Umbraco.Media(CurrentPage.topLevelImage);
}

<div style="text-align:center; width:100%; height:325px; background-size:cover; background-image: url(@src.Url);">
    <div id="transparentBox">
        <img id="theImage" src="~/images/THE.png" />
        <h3>@CurrentPage.name</h3>
    </div>
</div>

<div class="row" id="blackBox">
    <div class="container">
        @*<div class="text-center">
            <h4 style="  border-bottom: 1px solid #ffffff;width: 25%; margin: auto; padding: 10px;">FRANCHISE</h4>
        </div><br />*@
        <div class="text-center" style="margin-bottom:15px;">
            <h6>@CurrentPage.headingParagraph</h6>
        </div>

        <div class="row">
            <div class="col-sm-6">
                @CurrentPage.leftParagraph
            </div>
            <div class="col-sm-6">
                @CurrentPage.rightParagraph
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="container" style="margin-top:50px;">     
        <div id="storeDescription">
            @CurrentPage.bottomDescription
        </div>      
    </div>
</div>

@{Html.RenderPartial("_FooterBlock");}

CoffeeClubFranchise/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var src = Umbraco.Media(CurrentPage.topLevelImage);
}
<div style="text-align:center; width:100%; height:325px; background-size:cover; background-image: url(@src.Url);">
    <div id="transparentBox">
        <h3>@CurrentPage.name</h3>
    </div>
</div>

<div class="row" id="blackBox">
    <div class="container">
        <div class="text-center">
            @*<h4 style="  border-bottom: 1px solid #ffffff;width: 25%; margin: auto; padding: 10px;">@CurrentPage.name</h4>*@
        </div><br />   
    </div>
</div>


<div class="row">
    <div class="container">
        <div class="row">
            @{
                if (TempData["Success"] != null)
                {
                    <div class="alert alert-success alert-block fade in" id="successAlert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <p>@TempData["Success"]</p>
                    </div><!-- end alert -->
                }
            }

            <div class="col-md-6" style="padding:0px">
                @{Html.RenderAction("ContactForm", "Contact");  }
            </div>


            <div class="col-md-6">
                <div class="row" style="padding:20px;">
                    <div class="col-md-12">
                        @CurrentPage.rightContent
                    </div>

                </div>
            </div>


        </div>
    </div>
</div>
@{Html.RenderPartial("_FooterBlock");}

@section Javascript
{
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/jquery.validate.unobtrusive.min.js"></script>
}

CoffeeClubFranchise/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var m = Umbraco.Media(CurrentPage.homepageImage);
}

@*@CurrentPage.GetGridHtml("content", "fanoe")*@



@*<img src="@m.Url" alt="@m.UrlName" id="homePageImage" />*@

<div id="homeBlock" style="background-image:url('@m.Url');">
    <div id="centerPortion">
            @{Html.RenderPartial("_centerBlockHomePage");}
    </div>
    <div id="centerPortionOnMobile">
        <div class="visible-sm visible-xs" id="responsiveFooterBlock">
            <ul>
                <li><a href="/benefits">FRANCHISE BENEFITS</a></li>
                <li><a href="/opportunities">FRANCHISE OPPORTUNITIES</a></li>
                <li><a href="/application">FRANCHISE APPLICATION</a></li>
            </ul>
        </div>
    </div>


</div>







@section Javascript{

<script type="text/javascript" language="JavaScript">
  function set_body_height() { // set body height = window height
    $('body').height($(window).height());
  }
  $(document).ready(function() {
    $(window).bind('resize', set_body_height);
    set_body_height();
  });
</script>

}

CoffeeClubFranchise/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
	var home = @CurrentPage.Site();
    var currentPage = @CurrentPage.name;
}

<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, maximum-scale=1, user-scalable=no">
      <meta name="keywords" content="@(CurrentPage.metaKeywords != null ? CurrentPage.metaKeywords : "")" />
      <meta name="description" content="@(CurrentPage.metaDescription != null ? CurrentPage.metaDescription : CurrentPage.siteDescription)  ">

    <title>@CurrentPage.Name | @CurrentPage._siteTitle</title>
	
	<!-- Fonts -->
	<link href="//fonts.googleapis.com/css?family=Merriweather:400,700,300,900" rel="stylesheet" type="text/css">
	<link href="//fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet" type="text/css">
	
    <link rel='shortcut icon' href='favicon.ico' type='image/x-icon' /> 
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/fanoe.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
      <link href="/css/Live.css" type="text/css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
      <script src="/js/jquery.min.js"></script>     
     
  </head>

<body style="@(currentPage == "Home" ? "overflow:hidden; height:100%;" : "")">
    <header>
        <div class="container">
            <div class="row" style="position:relative;">
                <div class="col-xs-8 col-sm-12 col-md-2">
                    <a href="@home.Url">
                        <div class="brand" style="background-image:url('@(home.SiteLogo)')"></div>
                    </a>
                </div>
                @*<img class="hidden-sm hidden-xs" id="magnifyIcon" src="/media/magnifying.png" />*@
                @*<div class="col-sm-12 col-md-8">
                        <nav>

                            @{ Html.RenderPartial("MainNavigation"); }
                        </nav>
                    </div>*@

            </div>
        </div>

        <div class="col-sm-12 col-md-12">
            <div class="container">
                <nav>
                    @{ Html.RenderPartial("MainNavigation"); }
                </nav>
            </div>
        </div>

        <div id="toggle" class="toggle">
            <a href="#" class="cross"><span></span></a>
        </div>
    </header>

   
        @RenderBody()
    

    <footer style="background:rgba(0,0,0, 0.8);padding: 0px; margin-top:0px; height:50px; @(currentPage == "Home" ? "position:absolute;bottom:0;width:100%" : "")" class="row field dark">
        <div class="container" style="position:relative">
            <div class="row">

                @{ Html.RenderPartial("BottomNavigation"); }

            </div>
        </div>
    </footer>

    <!-- Javascripts -->
    @*<script src="/js/jquery.min.js"></script>*@
    <script src="/js/bootstrap.min.js"></script>
    <script src="/scripts/fanoe.js"></script>
    @*<script src="/js/jquery.nicescroll.min.js"></script>
    <script>
        $(document).ready(function () {
            $("html").niceScroll({ horizrailenabled: false });
        });
    </script>*@
    @RenderSection("Javascript", false)
    
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		ga('create', 'UA-67854777-2', 'auto');
		ga('send', 'pageview');
		
   </script>

</body>
</html>

CoffeeClubFranchise/Views/NewOpportunities.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var src = Umbraco.Media(CurrentPage.topLevelImage);
    var m = Umbraco.Media(CurrentPage.threeStoreImage);
}

<div style="text-align:center; width:100%; height:325px; background-size:cover; background-image: url(@src.Url);">
    <div id="transparentBox">
        <img id="theImage" src="~/images/THE.png" />
        <h3>@CurrentPage.name</h3>
    </div>
</div>

<div class="row" id="blackBox">
    <div class="container">
        @*<div class="text-center">
            <h4 style="  border-bottom: 1px solid #ffffff;width: 25%; margin: auto; padding: 10px;">STORE TYPES</h4>
        </div><br />*@
        <div class="text-center" style="">
            <h6>@CurrentPage.storeDescriptionHeader</h6>
        </div>
        
      
          @CurrentPage.storeDescription
     
    </div>
</div>
<div class="row">
    <div class="container">
        <div class="text-center">
            @*<h4 style="margin: 10px auto; padding: 10px;">THE THREE STORE MODELS WITHIN THE COFFEE CLUB ARE</h4>*@
            <h4 style="margin: 10px auto; padding: 10px;">@CurrentPage.imageHeading</h4>
        </div>
        

        <div class="text-center">
            @*<h4 style="  border-bottom: 1px solid #000000;width: 40%; margin: auto; padding: 10px;">SITES AND STORES AVAILABLE</h4>*@
            <h4 style="  margin: auto; padding: 10px;">@CurrentPage.bottomHeading</h4>
        </div>

        <div id="storeDescription">
            @CurrentPage.bottomDescription
        </div>
    </div>
</div>


@{Html.RenderPartial("_FooterBlock");}

CoffeeClubFranchise/Views/NormalPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
    var src = Umbraco.Media(CurrentPage.topLevelImage);
    var m = Umbraco.Media(CurrentPage.image);
}

<div style="text-align:center; width:100%; height:325px; background-size:cover; background-image: url(@src.Url);">
    <div id="transparentBox">
        <img id="theImage" src="~/images/THE.png" />
        <h3>@CurrentPage.name</h3>
    </div>
</div>

<div class="row" id="blackBox">
    <div class="container">
        @*<div class="text-center">
            <h4 style="  border-bottom: 1px solid #ffffff;width: 25%; margin: auto; padding: 10px;">@CurrentPage.name</h4>
        </div><br />*@
        <div class="text-center" style="">
            <h6>@CurrentPage.descriptionHeading</h6>
        </div>

        <div class="row">
            <div class="col-sm-6">
                @CurrentPage.leftParagraph
            </div>
            <div class="col-sm-6">
                @CurrentPage.rightParagraph
            </div>

        </div>
      

    </div>
</div>

<div class="row">
    <div class="container" style="margin-top:50px;">      
        <img src="@m.Url" alt="The Coffee Club" />  

        <div id="storeDescription">
            @CurrentPage.bottomDescription
        </div>

        @if (!string.IsNullOrEmpty(CurrentPage.youtubeUrl))
        {
            <div id="UVideo" class="text-left">
            </div>
        }
    </div>
</div>
@{Html.RenderPartial("_FooterBlock");}

<script type="text/javascript">
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = false;
    ga.src = 'http://www.youtube.com/player_api';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
    var done = false;
    var player;

    function onYouTubePlayerAPIReady() {
        var url = '@CurrentPage.youtubeUrl';
        var regExp = /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#\&\?]*).*/;
        var Id = '';
        var match = url.match(regExp);
        if (match && match[7].length == 11) {
            Id = match[7];
        } else {
            //alert("Could not extract video ID.");
        }

        player = new YT.Player('UVideo', {
           // height: '390',
            width: '100%',
            videoId: Id,
            playerVars: {
                controls: 0,
                disablekb: 1,
                showinfo:0
            },
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }
    function onPlayerReady(evt) {
        //console.log('onPlayerReady', evt);
    }
    function onPlayerStateChange(evt) {
        //console.log('onPlayerStateChange', evt);
        //if (evt.data == YT.PlayerState.PLAYING && !done) {
        //    setTimeout(stopVideo, 6000);
        //    done = true;
        //}
    }
    function stopVideo() {
        //console.log('stopVideo');
        //player.stopVideo();
    }
</script>

CoffeeClubFranchise/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@CurrentPage.GetGridHtml("content", "fanoe")